### PR TITLE
Hotfix: Results directory was not being created causing FileNotFound Error

### PR DESCRIPTION
**Pull request by 2320sharon**
# Hotfix: Results directory was not being created causing FileNotFound Error

When a user attempted to save the results of their segmentations a FileNoutFound Error would occur due to the results directory not existing. This hotfix adds a check for the results directory before it is used to store any segmentation data in.
```
        self.info.update('Saving results...', 'success')
        root_res_dir = pathlib.Path('results')
# Here is the new code 
# -------------------------------------
        if not root_res_dir.exists():
            root_res_dir.mkdir()
# ----------------------------------
        
        now = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
        print(now)
        res_dir = root_res_dir / now
        print(res_dir)
        res_dir.mkdir()
```

### CODE REVIEW

**Comment by maximlt** [comment]
Thanks @2320sharon !

It seems like you've submitted the notebook with its output, which includes a lot of javascript code and makes reviewing it difficult. You're not to be blamed though, notebooks and git can be quite a pain to deal with, we (the holoviz team) use a small internal tool to strip all the output and metadata of notebooks before pushing them when we want them to contain only the source (markdown + code) and no extras.

But since you've shown your diff in your message I've used it and pushed a fix similar to yours in this commit: https://github.com/pyviz-topics/holodoodler/commit/6e268790b35cfb51b73af62b9f56fa8a52caa407

**Comment by maximlt** [comment]
Closing in favor of the commit mentioned above, thanks again @2320sharon !

**Comment by 2320sharon** [comment]
Hi @maximlt !

Thank you for fixing this and integrating the changes.

When I was working the jupyter notebook with git I noticed all the metadata and wrongfully assumed it would just get absorbed into the notebook when it was merged. Thanks for letting me know that was not the case haha. 

If you don't mind what kinds of tools or practices should I use to strip unneeded meta data from notebooks for future merges?

**Comment by jbednar** [comment]
Thanks, @2320sharon ! The most important rule for notebooks on any holoviz or pyviz repo is to commit them with the output cleared, which you can easily do in Jupyter. That gets rid of 99% of the confusing diffs. In our group we go further and strip all the extra fiddly metadata that differs between systems so that we focus specifically on the code changes, and we have a script `strip_kernel` to do so:

```
#!/bin/bash
cp "$1" /tmp/
/usr/local/bin/jq --sort-keys --indent 1 \
    '
    (.cells[] | select(has("outputs")) | .outputs) = []
    | (.cells[] | select(has("execution_count")) | .execution_count) = null
    | .metadata = {"language_info": {"name":"python", "pygments_lexer": "ipython3"}}
    | .cells[].metadata = {}
    | del(.cells[].id)
    ' "$1" > /tmp/$(basename $1) && cat /tmp/$(basename $1) > "$1"
```

If you put this script somewhere in your path and have `jq` installed at the indicated location, then run it as `strip_kernel file.ipynb`, it should strip out all the extra stuff and leave just the diff that you want. But even if you just strip the output cells and not the metadata like this, it should still be reviewable and mergeable; we know how to ignore that stuff. :-)

**Pull request closed without merging**
